import = [
"~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
startup_mode = "Fullscreen"
decorations = "None"
opacity = 0.95

[cursor]
style = { shape = "Underline", blinking = "On" }

[shell]
program = "/bin/fish"

[font]
size = 11.25
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

