[general]
import = [
"~/.config/alacritty/themes/tokyo_night_enhanced.toml"
]

[window]
startup_mode = "Fullscreen"
decorations = "None"
opacity = 0.75

[cursor]
style = { shape = "Underline", blinking = "On" }

[terminal.shell]
program = "/usr/local/bin/zsh"
args = ["--login"]

[font]
size = 11.00
normal = { family = "JetBrains Mono Nerd Font", style = "Medium" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
