import = [
"~/.config/alacritty/tokyonight_night.toml"
]

[window]
startup_mode = "Fullscreen"
decorations = "None"
opacity = 1.00

[cursor]
style = { shape = "Underline", blinking = "On" }

[shell]
program = "/usr/local/bin/zsh"
args = ["--login"]

[font]
size = 11.00
normal = { family = "JetBrains Mono Nerd Font", style = "Medium" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
