[colors]
foreground = "#ffffff"
background = "#16181a"
cursor_bg = "#ffffff"
cursor_fg = "#16181a"
cursor_border = "#ffffff"
selection_fg = "#ffffff"
selection_bg = "#3c4048"
scrollbar_thumb = "#16181a"
split = "#16181a"

ansi = [ "#16181a", "#ff6e5e", "#5eff6c", "#f1ff5e", "#5ea1ff", "#bd5eff", "#5ef1ff", "#ffffff" ]
brights = [ "#3c4048", "#ff6e5e", "#5eff6c", "#f1ff5e", "#5ea1ff", "#bd5eff", "#5ef1ff", "#ffffff" ]

[colors.tab_bar]
background = "#16181a"
inactive_tab_edge = "#ffffff"

[colors.tab_bar.active_tab]
bg_color = "#16181a"
fg_color = "#7b8496"

[colors.tab_bar.inactive_tab]
bg_color = "#16181a"
fg_color = "#3c4048"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#16181a"
fg_color = "#7b8496"
italic = true

[colors.tab_bar.new_tab]
bg_color = "#16181a"
fg_color = "#7b8496"

[colors.tab_bar.new_tab_hover]
bg_color = "#16181a"
fg_color = "#7b8496"
intensity = "Bold"
