lua require('_settings')
lua require('_lazy')
lua require('_treesitter')
lua require('_lualine')
lua require('_lsp')
lua require('_colors')
lua require('_telescope')
lua require('_leap')
lua require('_twilight')
lua require('_zen-mode')
lua require('_maps')
lua require('_autocmd')

