#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5
filetype="$( file -Lb --mime-type "$file")"
if [[ "$filetype" =~ ^image ]]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
    exit 1
fi
if [[ "$filetype" == "application/pdf" ]]; then
    pdftoppm -jpeg -f 1 -singlefile "$file" "$CACHE"
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "${CACHE}.jpg" < /dev/null > /dev/tty
    exit 1
fi
if [[ "$filetype" =~ ^audio ]]; then
    mediainfo "$file"
    exit 1
fi
if [[ "$filetype" =~ ^video ]]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$(~/scripts/vidthumb.bash "$file")" < /dev/null > /dev/tty
    exit 1
fi
if [[ $(basename "$file") == *.md ]]; then
	glow "$file"
	exit 1
fi
if [[ $(basename "$file") == *.json ]]; then
	jq -C . "$file"
	exit 1
fi
~/Downloads/prog/pistol "$file"
