autoload -U colors && colors

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/histfile

export PATH="${PATH}:$HOME/.local/bin"

#xdg
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

#export NO_COLOR=1
export EDITOR="$HOME/neovim/bin/nvim"
export MANPAGER="$HOME/neovim/bin/nvim +Man!"
export BAT_THEME='ansi'

#clean home directory
export IPFS_PATH="$XDG_DATA_HOME"/ipfs
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export NVM_DIR="$XDG_DATA_HOME"/nvm
export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass
export DVDCSS_CACHE="$XDG_DATA_HOME"/dvdcss
export ELECTRUMDIR="$XDG_DATA_HOME"/electrum

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

setopt EXTENDED_GLOB
setopt GLOB_COMPLETE
setopt CORRECT

autoload edit-command-line; zle -N edit-command-line

bindkey -v
bindkey '^e' edit-command-line

bindkey '^[[1;2C' forward-word

zstyle ':completion:*' menu select
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate

autoload -U compinit && compinit
autoload -U promptinit && promptinit

eval "$(zoxide init zsh)"
eval "$(starship init zsh)"

xset r rate 300 50

source ~/.config/broot/launcher/bash/br
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/zsh-autosuggestions.zsh
source ~/.config/zsh/zsh-you-should-use.plugin.zsh
source ~/.config/zsh/zsh-syntax-highlighting.zsh
