autoload -U colors && colors

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/histfile

#export NO_COLOR=1
export EDITOR="$HOME/neovim/bin/nvim"
export MANPAGER="$HOME/neovim/bin/nvim +Man!"
export BAT_THEME='ansi'

echo "$PATH" | grep -qc "$HOME/.local/bin" || export PATH="$PATH:$HOME/.local/bin"

setopt EXTENDED_GLOB
setopt GLOB_COMPLETE

autoload edit-command-line; zle -N edit-command-line

bindkey -v
bindkey '^e' edit-command-line

bindkey '^[[1;2C' forward-word

zstyle ':completion:*' menu select
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate

autoload -U compinit && compinit

eval "$(zoxide init zsh)"
eval "$(starship init zsh)"

xset r rate 300 50

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

source ~/.config/broot/launcher/bash/br
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/zsh-autosuggestions.zsh
source ~/.config/zsh/zsh-you-should-use.plugin.zsh
source ~/.config/zsh/zsh-syntax-highlighting.zsh
