autoload -U colors && colors

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/histfile

setopt EXTENDED_GLOB

autoload edit-command-line; zle -N edit-command-line

bindkey -v
bindkey '^e' edit-command-line

bindkey '^[[1;2C' forward-word

zstyle ':completion:*' menu select

autoload -U compinit && compinit

eval "$(zoxide init zsh)"
eval "$(starship init zsh)"

source ~/.config/broot/launcher/bash/br
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/zsh-autosuggestions.zsh
source ~/.config/zsh/zsh-you-should-use.plugin.zsh
source ~/.config/zsh/zsh-syntax-highlighting.zsh
